#!/bin/sh -e
loc=$1
if [ "$loc" = ""]; then
    read -p "[?] Please specify a location to install the trusty cli chroot: " loc
    if [ "$loc" = "" ] || [ ! -d "$loc" ]; then
        echo "[*] Cannot continue with bad location: $loc"
    fi
fi
sudo crouton -e -n vs -p $loc -r trusty -t audio,cli-extra,core,extension,x11,xorg && {
    chstartgen vs $loc enter-chroot && {
        chupdategen vs $loc trusty audio,cli-extra,core,extension,x11,xorg
    }
}
